# Generated by Django 6.0 on 2025-12-26 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Namn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategorier',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Namn')),
                ('contact_type', models.CharField(choices=[('healthcare', 'Sjukvård'), ('psychiatry', 'Psykiatri'), ('psychology', 'Psykolog'), ('counselor', 'Kurator'), ('social_services', 'Socialtjänst'), ('contact_person', 'Kontaktperson'), ('housing_support', 'Boendestöd'), ('support_person', 'Stödperson'), ('family', 'Familj'), ('friend', 'Vän'), ('other', 'Övrigt')], default='other', max_length=20, verbose_name='Kontakttyp')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-postadress')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Organisation')),
                ('address', models.TextField(blank=True, verbose_name='Besöksadress')),
                ('notes', models.TextField(blank=True, verbose_name='Anteckningar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Uppdaterad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.contactcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakter',
                'ordering': ['name'],
            },
        ),
    ]
