# Generated by Django 6.0 on 2025-12-21 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Namn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etikett',
                'verbose_name_plural': 'Etiketter',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.IntegerField(blank=True, choices=[(1, 'Väldigt dåligt'), (2, 'Dåligt'), (3, 'Okej'), (4, 'Bra'), (5, 'Väldigt bra')], null=True, verbose_name='Humör')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Antal timmar sömn')),
                ('sleep_quality', models.IntegerField(blank=True, choices=[(1, 'Väldigt dålig'), (2, 'Dålig'), (3, 'Okej'), (4, 'Bra'), (5, 'Väldigt bra')], null=True, verbose_name='Sömnkvalitet')),
                ('energy_level', models.IntegerField(blank=True, help_text='1-10', null=True, verbose_name='Energinivå')),
                ('anxiety_level', models.IntegerField(blank=True, help_text='1-10', null=True, verbose_name='Ångestnivå')),
                ('grateful_for', models.TextField(blank=True, help_text='Något positivt från dagen', verbose_name='Tacksam för')),
                ('looking_forward_to', models.TextField(blank=True, help_text='Något att se fram emot imorgon', verbose_name='Ser fram emot')),
                ('affirmation', models.TextField(blank=True, help_text='Något du vill säga till dig själv', verbose_name='Dagens påminnelse')),
                ('content', models.TextField(blank=True, help_text='Skriv fritt', verbose_name='Dagbok')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fäst inlägg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='journal.journaltag', verbose_name='Etiketter')),
            ],
            options={
                'verbose_name': 'Dagboksinlägg',
                'verbose_name_plural': 'Dagboksinlägg',
                'ordering': ['-is_pinned', '-date', '-created_at'],
            },
        ),
    ]
