# Generated by Django 6.0 on 2025-12-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, 'Väldigt dåligt'), (2, 'Dåligt'), (3, 'Ganska dåligt'), (4, 'Lite dåligt'), (5, 'Neutralt'), (6, 'Lite bra'), (7, 'Ganska bra'), (8, 'Bra'), (9, 'Väldigt bra'), (10, 'Fantastiskt'), (11, 'Bästa möjliga')], null=True, verbose_name='Humör'),
        ),
    ]
